version: "3.8"

services:
  app:
    container_name: php-cli
    build:
      context: .
      dockerfile: _docker/php/cli/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/php/cli/php.ini:/usr/local/etc/php/conf.d/php.ini
#    user: 1000:1000
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t /var/www/public

#  app:
#    container_name: php-fpm
#    build:
#      context: .
#      dockerfile: _docker/php/fpm/Dockerfile
#    volumes:
#      - ./:/var/www
#      - ./_docker/php/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
#    depends_on:
#      - db
##    user: 1000:1000

  #  nginx:
  #    image: nginx:latest
  #    container_name: nginx
  #    volumes:
  #      - ./:/var/www
  #      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
  #    ports:
  #      - "8077:80"
  #    depends_on:
  #      - app

  db:
    image: postgres:16.1
    container_name: postgres
    volumes:
#      - ./tmp/db/postgres:/var/lib/postgresql # not save
      - ./tmp/db/postgres:/var/lib/postgresql/data # save
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

#  db:
#    image: mysql:8.0
#    container_name: mysql
#    restart: always
#    volumes:
#      - ./tmp/db/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_DATABASE}
#    ports:
#      - "8111:8111"
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --port=8111